#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs dev /dev
mount -t tmpfs tmpfs /run
udevd --daemon
udevadm trigger -t subsystems -c add
udevadm trigger -c add
udevadm settle
R=$(sed 's/.* \?root=\([^ ]*\).*/\1/p;d' /proc/cmdline)
for D in 1 2 3; do
	case $R in
	UUID=*) D=/dev/disk/by-uuid/${R#UUID=};;
	[0-9a-fA-F]*) D=/dev/block/$((0x0$R>>8)):$((0x0$R&0xff));;
	*) D=$R
	esac
	D=$(readlink -e "$D")
	[ -z "$D" ] || break
	sleep 1
done
for D in $D $(sed '1,2d;s%.* \([^ ]*\)$%/dev/\1%' /proc/partitions); do
	mount $D /mnt || continue
	if [ -x /mnt/sbin/init ]; then
		echo Switching root to $D ...
		udevadm control --exit
		exec switch_root /mnt /sbin/init
	fi
	umount /mnt
done
echo Root device not found
sleep 1h
