#!/bin/sh
mount --bind /proc /mnt/proc
mount --bind /sys /mnt/sys
mount --bind /dev /mnt/dev
mount --bind /dev/pts /mnt/dev/pts
mount --bind /run /mnt/run
mount --bind /tmp /mnt/tmp
chroot /mnt /bin/sh
