#!/bin/sh
#
# /etc/rc.d/snmpd: snmpd(8) management
#

SSD=/sbin/start-stop-daemon
PRG=/usr/sbin/snmpd
PID=/run/snmpd.pid
OPT="-A -p $PID -Ls 7 -u snmp -g snmp"

case $1 in
start)
	$SSD --start --pidfile $PID --exec $PRG -- $OPT
	;;
stop)
	$SSD --stop --pidfile $PID --remove-pidfile --retry 10
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	$SSD --status --pidfile $PID
	case $? in
	0) echo $PRG is running;;
	1) echo $PRG is not running but the pid file $PID exists;;
	3) echo $PRG is not running;;
	4) echo Unable to determine $PRG status;;
	esac
	;;
*)
	echo "Usage: $0 [start|stop|restart|status]"
	;;
esac
